### ISSUE TITLE
Make this repo private?

### ISSUE THREAD

**Issue by deldersveld** [Microsoft/powerbi-visuals-image-comparison-tests#8]
Should this repo be public?
- It contains screenshots of two unreleased visuals (Flywheel and PowerKPI)
- The embedded-reports-urls.config.json file contains links to Publish to Web reports in two environments public doesn't use (dxt and msit)
- Flywheel Publish to Web report contains non-public data such as the unique number of active BAPI users and info about ISV and SIs

**Comment by ignatvilesov** [comment]
+ pbiviz support

**Comment by uve** [comment]
All embeds in this repository should contain a sample data only.
+@savvinsergey, please look into it.
During investigation, I’ll switch this repo to private.

**Comment by savvinsergey** [comment]
I changed dataset for Flywheel. Now it doesn't contain non-public data
